#!/bin/sh
module="short"
device="short"
mode="664"

# Group: since distributions do it differently, look for wheel or use staff
if grep '^staff:' /etc/group > /dev/null; then
    group="staff"
else
    group="wheel"
fi


# invoke insmod with all arguments we got
# and use a pathname, as newer modutils don't look in . by default
/sbin/insmod ./$module.ko $* || exit 1

major=`cat /proc/devices | awk "\\$2==\"$module\" {print \\$1}"`

# Create 8 entry points, as SHORT_NR_PORTS is 8 by default
rm -f /dev/${device}0
echo ${device}
mknod /dev/${device}0 c $major 0


chgrp $group /dev/${device}
chmod $mode  /dev/${device}  






